//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDevicesNetwork.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartDevicesNetwork.WebApi.Resources.ApiMessages", typeof(ApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action {0} was not found.
        /// </summary>
        internal static string ActionNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("ActionNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device wasn&apos;t found.
        /// </summary>
        internal static string DeviceNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("DeviceNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device rebooted successfully.
        /// </summary>
        internal static string DeviceRebootedSuccessMessage {
            get {
                return ResourceManager.GetString("DeviceRebootedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reboot device.
        /// </summary>
        internal static string DeviceRebootErrorMessage {
            get {
                return ResourceManager.GetString("DeviceRebootErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device reboot was started successfully.
        /// </summary>
        internal static string DeviceRebootSuccessMessage {
            get {
                return ResourceManager.GetString("DeviceRebootSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to switch off device.
        /// </summary>
        internal static string DeviceSwitchedOffErrorMessage {
            get {
                return ResourceManager.GetString("DeviceSwitchedOffErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device switched off.
        /// </summary>
        internal static string DeviceSwitchedOffMessage {
            get {
                return ResourceManager.GetString("DeviceSwitchedOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device switched off successfully.
        /// </summary>
        internal static string DeviceSwitchedOffSuccessMessage {
            get {
                return ResourceManager.GetString("DeviceSwitchedOffSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to switch on device.
        /// </summary>
        internal static string DeviceSwitchedOnErrorMessage {
            get {
                return ResourceManager.GetString("DeviceSwitchedOnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device switched on successfully.
        /// </summary>
        internal static string DeviceSwitchedOnSuccessMessage {
            get {
                return ResourceManager.GetString("DeviceSwitchedOnSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled internal server error.
        /// </summary>
        internal static string UnhandledServerErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledServerErrorMessage", resourceCulture);
            }
        }
    }
}
