name: "Setup .NET and check project"
description: "Sets up .NET SDK and checks the project for formatting, code analysis, and runs unit tests."

inputs:
  dotnet-version:
    required: true
    default: "10.0.x"
  project-name:
    required: true
    default: "SmartDevicesNetwork.WebApi"
  
runs:
  using: "composite"
  steps:
    - name: Set up dotnet
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Cache NuGet packages
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    # Even for cache-hit, we still need to restore assets (project.assets.json).
    - name: Restore
      run: dotnet restore
      shell: bash

    - name: Build
      run: dotnet build ${{ inputs.project-name }} --configuration Release --no-restore
      shell: bash

    - name: Format check
      run: dotnet format --verify-no-changes
      shell: bash

    - name: Code analysis
      run: dotnet format analyzers --verify-no-changes
      shell: bash

    - name: Unit tests
      run: dotnet test
      shell: bash