name: Pull Request Check

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ master ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      build-result: ${{ steps.build.outputs.result }}
      format-result: ${{ steps.format.outputs.result }}
      analyze-result: ${{ steps.analyze.outputs.result }}
      test-result: ${{ steps.test.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        id: build
        run: |
          set +e
          dotnet build SmartDevicesNetwork.WebApi
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failed" >> $GITHUB_OUTPUT
          fi
      
          set -e
          exit $exit_code

      - name: Format check
        id: format
        run: |
          set +e
          dotnet format --verify-no-changes
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failed" >> $GITHUB_OUTPUT
          fi
          
          set -e
          exit $exit_code

      - name: Code analysis
        id: analyze
        run: |
          set +e
          dotnet format analyzers --verify-no-changes
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failed" >> $GITHUB_OUTPUT
          fi
          
          set -e
          exit $exit_code

      - name: Unit tests
        id: test
        run: |
          set +e
          dotnet test
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failed" >> $GITHUB_OUTPUT
          fi
          
          set -e
          exit $exit_code
  
  create-pr-comment:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
      - name: Create or update success PR comment
        if: ${{ needs.build.result == 'success' }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### CI Status ✔
            
            **Build:** Success 
            **Format:** Success  
            **Analyze:** Success  
            **Tests:** Success  
            
            🟢 All checks passed — ready for merge.
            
      - name: Create or update failure PR comment
        if: ${{ needs.build.result == 'failure' }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### CI Status ❌
            
            **Build:** ${{ needs.build.outputs.build-result }}  
            **Format:** ${{ needs.build.outputs.format-result }}  
            **Analyze:** ${{ needs.build.outputs.analyze-result }}  
            **Tests:** ${{ needs.build.outputs.test-result }}  
            
            🔴 Some checks failed — please review the logs and fix the issues.