name: Working with Actions

on:
  workflow_dispatch:
    
env:
  PROJECT_NAME: SmartDevicesNetwork.WebApi
  WEB_API_DOCKER_IMAGE: smart-devices-network-api.tar

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up dotnet via composite action
        uses: ./.github/actions/setup-dotnet
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}
          project-name: ${{ env.PROJECT_NAME }}
          
      - name: Save Docker image
        run: |
          docker save smart-devices-network-api:latest -o ${{ env.WEB_API_DOCKER_IMAGE }}

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapi-docker-image
          path: ${{ env.WEB_API_DOCKER_IMAGE }}
      